Matrix Transpose(2D Arrays)
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #183
Opened 2021-03-18 16:46 UTC by sayantani11

Fixed issue #160 
Please review and suggest if any changes required.
Hoping for a feedback soon.
Thank you for letting me work for this issue.

2021-03-19 09:40 UTC, rohanbabbar04 requested changes

2021-03-19 09:40 UTC, rohanbabbar04 commented on Topic Wise Questions with Solutions/Array/Matrix_Transpose.py
> +    # For the matrix transpose:
Define a function for ease of understanding

2021-03-19 09:40 UTC, rohanbabbar04 commented on Topic Wise Questions with Solutions/Array/Matrix_Transpose.py
> +# input = 1 2 3
Add the sample output after the code

2021-03-19 15:41 UTC, sayantani11 commented
I did define it by a function

2021-03-20 10:38 UTC, rohanbabbar04 approved these changes

2021-03-21 05:22 UTC, sayantani11 commented
@rcoder23 The changes are approved.......isn't it done?

2021-03-22 14:03 UTC, sayantani11 commented
@rcoder23  Can you please update me?
The changes are approved....Then why the tag?

2021-03-22 15:37 UTC, rcoder23 approved these changes
Correct

2021-03-22 15:37 UTC, merged