Issue 29: Added Z algorithm in String
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #185
Opened 2021-03-18 17:21 UTC by Rutuja-Kolte

2021-03-23 07:58 UTC, rohanbabbar04 requested changes
Define a function and put the logic of the code there, use main for only driver code

2021-03-23 07:58 UTC, rohanbabbar04 commented on String/Z-Algorithm.py
> +
Use dynamic input

2021-03-23 07:58 UTC, rohanbabbar04 commented on String/Z-Algorithm.py
> +
Add sample I/O

2021-03-25 02:11 UTC, Joshitha18 commented
@Rutuja-Kolte do changes as requested.

2021-03-25 02:15 UTC, Rutuja-Kolte commented on String/Z-Algorithm.py
> +
will do so

2021-04-17 05:25 UTC, closed without merging