Wave Sort
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #221
Opened 2021-03-22 14:41 UTC by sayantani11

Sorry for being late
Here's issue #184

2021-03-23 05:46 UTC, rohanbabbar04 requested changes

2021-03-23 05:46 UTC, rohanbabbar04 commented on Algorithms/Sorting/Wave_Sort.py
> +        numbers.append(elements)
Use list map instead of using a for loop

2021-03-23 10:35 UTC, sayantani11 commented
@rohanbabbar04 done!

2021-03-23 10:35 UTC, sayantani11 commented
@rohanbabbar04 done!

2021-03-23 11:55 UTC, rohanbabbar04 requested changes
Add sample I/O at the end of the code

2021-03-23 11:55 UTC, rohanbabbar04 commented on Algorithms/Sorting/Wave_Sort.py
> +
Remove extra lines

2021-03-23 11:55 UTC, rohanbabbar04 commented on Algorithms/Sorting/Wave_Sort.py
> +
remove extra line

2021-03-24 15:33 UTC, sayantani11 commented
@rohanbabbar04 is it okay?

2021-03-24 18:23 UTC, rohanbabbar04 requested changes

2021-03-24 18:23 UTC, rohanbabbar04 commented on Algorithms/Sorting/Wave_Sort.py
> +
Use docstrings instead of #

2021-03-29 13:28 UTC, sayantani11 commented
@rcoder23 The issue isn't reviewed yet

2021-03-30 17:52 UTC, rohanbabbar04 commented
@sayantani11 You have still not used docstrings (''') 
Use ''' for multiple line comment instead of #

2021-04-01 14:47 UTC, rohanbabbar04 approved these changes

2021-04-01 16:26 UTC, sayantani11 commented
@rcoder23 please merge

2021-04-02 02:53 UTC, rcoder23 requested changes
Try to add input and output statement together

2021-04-02 02:53 UTC, rcoder23 commented on Algorithms/Sorting/Wave_Sort.py
> + SAMPLE INPUT:
**Length of array:** statement missing

2021-04-02 02:53 UTC, rcoder23 commented on Algorithms/Sorting/Wave_Sort.py
> +    numbers = list(map(int, input().split()))
Error in the code , can be correct by 
**numbers = list(map(int, input().split(",")))**

2021-04-02 14:39 UTC, sayantani11 commented
@rcoder23 Please review

2021-04-03 02:41 UTC, rcoder23 approved these changes

2021-04-03 02:41 UTC, merged