Added shell_sort.py
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #225
Opened 2021-03-22 16:42 UTC by Harikrishnan6336

Fixes #192

2021-03-23 05:15 UTC, rohanbabbar04 approved these changes

2021-03-23 12:29 UTC, rcoder23 requested changes
Recheck your code .

2021-03-23 12:29 UTC, rcoder23 commented on Algorithms/Sorting/shell_sort.py
> +            ele = arr[i]
Producing Error **list index out of range**

2021-03-23 14:38 UTC, Harikrishnan6336 commented
I have tested the code with various edge case sample input outputs and then also wasnt able to find an occurence of such error!!.
Could you tell me for which test case the error is occuring. @rcoder23

2021-03-23 14:45 UTC, rohanbabbar04 requested changes

2021-03-23 14:45 UTC, rohanbabbar04 commented on Algorithms/Sorting/shell_sort.py
> +        if n == 0:
Unexpected Indent

2021-03-23 15:17 UTC, Harikrishnan6336 commented
Made the required changes.

2021-03-24 13:34 UTC, rcoder23 approved these changes

2021-03-24 13:35 UTC, merged