Trailing zeroes
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #230
Opened 2021-03-23 12:33 UTC by NEERAJAP2001

Solves #111

2021-03-23 13:47 UTC, NEERAJAP2001 commented
@rcoder23 This is the new PR, I've created a branch called"Traling_Zeroes" .

2021-03-23 13:56 UTC, rohanbabbar04 requested changes

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +
Remove extra line

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +
Remove extra line

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +    #initialise to 0
Self explanatory No need to explain each and every line

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +    # Till Number is graeter than zero loop will execute
Self explanatory

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +        # keep diving by 5
Self explanatory 
Don't write unless specific

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +        # add to rem
Self explanatory

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +    # rem has the answer
Self explanatory

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +# taking input
Self explanatory

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +# gtting the solution
Self explanatory 
Don't make the code long

2021-03-23 13:56 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +# printing to console
Self explanatory

2021-03-24 14:36 UTC, rohanbabbar04 requested changes

2021-03-24 14:36 UTC, rohanbabbar04 commented on Numerical/Trailing_Zeroes.py
> +# Explanation: 5! = 120
Use docstrings (''') instead of #

2021-03-24 18:35 UTC, rohanbabbar04 approved these changes

2021-03-25 05:01 UTC, rcoder23 approved these changes

2021-03-25 05:01 UTC, merged