Create Pollard's_rho_algorithm.py
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #271
Opened 2021-03-29 19:03 UTC by rupal121

issue #243 
Implemented Pollard's rho algorithm

2021-03-31 18:19 UTC, rupal121 commented
what changes you want? @rcoder23

2021-04-01 02:45 UTC, rcoder23 commented
@rupal121 Use docstring to explain code .

2021-04-01 07:46 UTC, rupal121 commented
@rcoder23 Kindly review

2021-04-01 14:57 UTC, rohanbabbar04 requested changes
Add a sample output at the end of the code
Use Dynamic output

2021-04-01 14:57 UTC, rohanbabbar04 commented on Algorithms/Integer Factorization Algorithm/Pollard's_rho_algorithm.py
> +from math import gcd
Use from fractions import gcd

2021-04-01 18:23 UTC, rupal121 commented
All the changes have been made. Kindly review @rcoder23 @rohanbabbar04

2021-04-02 02:33 UTC, rcoder23 requested changes
define what is Pollard's rho algorithm and add it in algorithms folder .without sub folder

2021-04-02 04:50 UTC, rupal121 commented
All suggested changes have been made. Kindly review @rcoder23 @rohanbabbar04

2021-04-02 12:05 UTC, rohanbabbar04 approved these changes

2021-04-02 16:54 UTC, rupal121 commented
Please list all the changes you want this time @rcoder23  so that I can finalize this issue after this.

2021-04-03 02:32 UTC, rcoder23 requested changes

2021-04-03 02:32 UTC, rcoder23 commented on Algorithms/Pollard's_rho_algorithm.py
> +        factor = gcd(x - y, number)
use Math.gcd

2021-04-03 02:32 UTC, rcoder23 commented on Algorithms/Pollard's_rho_algorithm.py
> +number=int(input())
Take input with message

2021-04-03 12:35 UTC, rupal121 commented
All changes have been made except "use math.gcd"  because @rohanbabbar04 said to use fractions library and you are asking to use math.gcd @rcoder23. Now please approve it @rcoder23.

2021-04-04 13:31 UTC, rcoder23 approved these changes

2021-04-04 13:32 UTC, merged