Added the required code
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #366
Opened 2021-04-26 04:48 UTC by srisatya1197

@rcoder23  I added the required code for the #340 . Please review it and let me know any changes to be made.

2021-04-28 02:52 UTC, rcoder23 requested changes
Add driver code also .

2021-05-02 08:35 UTC, srisatya1197 commented
@rcoder23 Can you please check now.

2021-05-03 03:22 UTC, rcoder23 requested changes
there is no connection Between driver code and solution code.

2021-05-03 03:22 UTC, rcoder23 commented on Topic Wise Questions with Solutions/Linked List/remove.py
> +i+=1
indention error

2021-05-03 03:22 UTC, rcoder23 commented on Topic Wise Questions with Solutions/Linked List/remove.py
> +val=int(input())
Take input with message

2021-05-09 03:12 UTC, srisatya1197 commented
@rcoder23 Sorry for the delay, I had some exams. Can you please check now I changed the code.

2021-05-14 10:24 UTC, srisatya1197 commented
@rcoder23 Can you please check this.

2021-05-17 04:37 UTC, srisatya1197 commented
@rcoder23 Can you please check?

2021-05-21 03:10 UTC, rcoder23 requested changes

2021-05-21 03:10 UTC, rcoder23 commented on Topic Wise Questions with Solutions/Linked List/remove.py
> +print("Enter the values for nums to store in an array:")
**Enter the values for nums to store in an array:**
change to **Enter the values for nums to store in an linkedist**

2021-05-21 03:10 UTC, rcoder23 commented on Topic Wise Questions with Solutions/Linked List/remove.py
> +print("Enter the value of val:")
**Enter the value of val to delete :**

2021-05-21 04:38 UTC, srisatya1197 commented
@rcoder23 Can you please check now ?

2021-05-24 08:18 UTC, srisatya1197 commented
@rcoder23 Can you please check now?

2021-05-31 11:56 UTC, srisatya1197 commented
@rcoder23 Can you please check this pr.

2021-06-01 03:08 UTC, rcoder23 approved these changes

2021-06-01 03:19 UTC, srisatya1197 commented
Is it merged @rcoder23 ?

2021-06-01 03:20 UTC, merged

2021-06-01 03:20 UTC, rcoder23 commented
@srisatya1197 Sorry I forget to merged.

2021-06-01 03:24 UTC, srisatya1197 commented
@rcoder23 thank you.