Kth index removal from a string
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #422
Opened 2021-05-13 07:38 UTC by Khushi-agarwal

Fixes #419

2021-05-13 07:39 UTC, Khushi-agarwal commented
Please review it. @rcoder23 @rashrey2308 .Thanks

2021-05-15 10:44 UTC, rcoder23 requested changes
recheck code

2021-05-15 10:44 UTC, rcoder23 commented on Dynamic Programming/Kth index in string.py
> +          print(s1)
extra indention

2021-05-15 11:07 UTC, Khushi-agarwal commented
@rcoder23 done the changes.Kindly review.

2021-05-15 11:08 UTC, Khushi-agarwal commented on Dynamic Programming/Kth index in string.py
> +          print(s1)
Done the changes.

2021-05-16 04:30 UTC, rcoder23 requested changes
Add solution in string folder

2021-05-16 05:44 UTC, Khushi-agarwal commented
@rcoder23 added to string folder

2021-05-17 05:30 UTC, Khushi-agarwal commented
@rashrey2308 @Joshitha18 kindly review my pr and merge it.Thanks.

2021-05-18 03:18 UTC, rcoder23 commented
@Khushi-agarwal Kth index in string.py rename file as Kth_index_remove.py

2021-05-18 06:26 UTC, Khushi-agarwal commented
> @Khushi-agarwal Kth index in string.py rename file as Kth_index_remove.py

Done.Kindly review.

2021-05-19 03:50 UTC, Khushi-agarwal commented
@rcoder23 please merge it if everything is right.Thanks.

2021-05-21 02:56 UTC, rcoder23 approved these changes

2021-05-21 02:56 UTC, merged