Added Noble Integer
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #429
Opened 2021-05-14 08:19 UTC by rohanbabbar04

Fixes #427 

Do review and merge @rcoder23

2021-05-15 10:39 UTC, rcoder23 requested changes

2021-05-15 10:39 UTC, rcoder23 commented on Algebra/Noble_Integer.py
> +'''
recheck output

2021-05-15 10:40 UTC, rcoder23 commented
@rohanbabbar04 make issue on data-structure. 
number types question not to much useful

2021-05-15 11:12 UTC, rohanbabbar04 commented
Ok sir will do

2021-05-15 16:47 UTC, rohanbabbar04 commented
@rcoder23 Done 
Do review and merge

2021-05-16 04:16 UTC, rcoder23 requested changes
in case of input :- 1 2 3 4 5
noble number should  be 1.
but it show 3

2021-05-16 04:25 UTC, rcoder23 commented
@rohanbabbar04 I search on google but i can't find appropriate explanations about noble number .
So ,I am closing this pull request .
You can work on Segment Tree #433 issue

2021-05-16 04:35 UTC, rohanbabbar04 commented
Here is the explanation Plz reopen and merge it
https://www.geeksforgeeks.org/noble-integers-in-an-array-count-of-greater-elements-is-equal-to-value/#:~:text=An%20integer%20x%20is%20said,greater%20than%203%20is%20three.

2021-05-16 04:40 UTC, rcoder23 commented
> in case of input :- 1 2 3 4 5
> noble number should be 1.
> but it show 3

@rohanbabbar04 Solve this

2021-05-16 04:42 UTC, rohanbabbar04 commented
It is showing No noble integer
In the question, noble integer is an integer where the number of elements greater than n is equal to n
In case of the question integers greater than 1 is equal to so can't be

2021-05-16 04:43 UTC, rohanbabbar04 commented
> It is showing No noble integer
> In the question, noble integer is an integer where the number of elements greater than n is equal to n
> In case of the question integers greater than 1 is equal to 4 so can't be

@rcoder23 do review

2021-05-16 04:48 UTC, merged