added activity selection problem
Developer-Student-Clubs-VSSUT-Burla/Master-PyAlgo pull request #501
Opened 2021-05-27 06:39 UTC by robin025

fixes #488 
added activity seclection problem

2021-06-03 03:31 UTC, rcoder23 requested changes
Add solution with explaination

2021-06-03 03:31 UTC, rcoder23 commented on greedy algorithms/Activity_Selection_problem.py
> +
remove spaces

2021-06-03 03:31 UTC, rcoder23 commented on greedy algorithms/Activity_Selection_problem.py
> +# 1.Entre  Activity       2.Exit
Use """       """    for comments

2021-06-03 03:52 UTC, robin025 commented on greedy algorithms/Activity_Selection_problem.py
> +
okay @rcoder23

2021-06-03 03:52 UTC, robin025 commented on greedy algorithms/Activity_Selection_problem.py
> +# 1.Entre  Activity       2.Exit
ok @rcoder23

2021-06-03 04:31 UTC, robin025 commented on greedy algorithms/Activity_Selection_problem.py
> +
Done @rcoder23

2021-06-03 04:31 UTC, robin025 commented on greedy algorithms/Activity_Selection_problem.py
> +# 1.Entre  Activity       2.Exit
Done @rcoder23

2021-06-03 04:31 UTC, robin025 commented
@rcoder23  maded changes as suggested

2021-06-04 03:01 UTC, rcoder23 approved these changes

2021-06-04 03:01 UTC, merged

2021-06-07 17:43 UTC, robin025 commented
Hello @rcoder23 ,
I had a discussion with Praveen who is doing all the leaderboard stuff of GSSoC21 and he told all of us that the GSSoC21 tag should look like *GSSoC21* and it's case sensitive, so if the tag doesn't look like this *GSSoC21* then that PR will not be counted, so can you please update the tag in all my PRs thatbhave reference to issue #488 
Note : there are only 4 PRs

Thankyou